version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: kdatlt/backend
    command: gunicorn --bind 0.0.0.0:8080 backend.wsgi
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - media:/app/media
    depends_on:
      - db


  frontend:
    container_name: frontend
    image: kdatlt/frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: nginx
    image: kdatlt/nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/backend_static/
      - media:/app/media
    depends_on:
      - backend
      - frontend
      - db